"""
VoiceShield AI — I4C-Ready Forensic Incident PDF Report Generator
Generates formal incident reports for the Indian Cyber Crime Coordination Centre (I4C).
All timestamps are in Indian Standard Time (IST, UTC+5:30).
"""

import os
import uuid
import logging
from datetime import datetime, timezone, timedelta
from typing import Dict, Any, Optional

from reportlab.lib.pagesizes import A4
from reportlab.lib import colors
from reportlab.lib.units import inch
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import (
    SimpleDocTemplate, Table, TableStyle, Paragraph, Spacer,
)

from app.engine.risk import risk_band, threshold_for, verdict_for

logger = logging.getLogger(__name__)

IST = timezone(timedelta(hours=5, minutes=30))


def _add_footer(canvas, doc):
    """Add page footer with page number and disclaimer."""
    canvas.saveState()
    canvas.setFont("Helvetica", 8)
    canvas.setFillColor(colors.grey)
    canvas.drawString(
        inch, 0.5 * inch,
        f"Generated by VoiceShield AI — Not a legal document  |  Page {doc.page}"
    )
    canvas.restoreState()


def _to_ist_str(ts: Any, *, suffix: bool = True) -> str:
    """Convert various timestamp formats to IST string.

    `suffix=False` drops the trailing " IST" (used in table cells whose column
    header already declares IST) so timestamps stay inside their column width.
    """
    fmt = "%Y-%m-%d %H:%M:%S IST" if suffix else "%Y-%m-%d %H:%M:%S"
    if ts is None:
        return "N/A"
    if isinstance(ts, datetime):
        return ts.astimezone(IST).strftime(fmt)
    if isinstance(ts, (int, float)):
        return datetime.fromtimestamp(ts, IST).strftime(fmt)
    if isinstance(ts, str):
        try:
            dt = datetime.fromisoformat(ts)
            if dt.tzinfo is None:
                # Naive strings are UTC in the store's contract (UUID-prefixed
                # ISO-8601); never treat them as local time before converting.
                dt = dt.replace(tzinfo=timezone.utc)
            return dt.astimezone(IST).strftime(fmt)
        except Exception:
            return ts
    return str(ts)


def generate_forensic_pdf(
    session_data: Dict[str, Any],
    output_path: str,
    blockchain: Optional[Dict[str, Any]] = None,
) -> str:
    """
    Generate a formal forensic incident PDF report.

    Args:
        session_data: Dict with keys:
            - call_id, role, start_time, end_time, peak_score,
              peak_prosodics, action_taken, history
        output_path: Absolute path to save the PDF.
        blockchain: Optional block dict to embed an on-ledger evidence receipt.

    Returns:
        The output_path on success.
    """
    os.makedirs(os.path.dirname(output_path) or ".", exist_ok=True)

    doc = SimpleDocTemplate(
        output_path,
        pagesize=A4,
        rightMargin=0.75 * inch,
        leftMargin=0.75 * inch,
        topMargin=0.75 * inch,
        bottomMargin=0.75 * inch,
    )

    styles = getSampleStyleSheet()

    # Custom styles
    title_style = ParagraphStyle(
        "TitleStyle", parent=styles["Heading1"],
        fontName="Helvetica-Bold", fontSize=18, alignment=1,
        spaceAfter=4, textColor=colors.HexColor("#1a237e"),
    )
    subtitle_style = ParagraphStyle(
        "SubtitleStyle", parent=styles["Normal"],
        fontName="Helvetica-Oblique", fontSize=11, alignment=1,
        spaceAfter=16, textColor=colors.HexColor("#c62828"),
    )
    heading_style = ParagraphStyle(
        "HeadingStyle", parent=styles["Heading2"],
        fontName="Helvetica-Bold", fontSize=13, spaceBefore=14,
        spaceAfter=6, textColor=colors.HexColor("#1a237e"),
    )
    normal_style = styles["Normal"]
    bullet_style = ParagraphStyle(
        "Bullet", parent=normal_style,
        leftIndent=20, bulletIndent=10, spaceAfter=4, fontSize=10,
    )
    cell_style = ParagraphStyle(
        "TblCell", parent=normal_style,
        fontName="Helvetica", fontSize=8, leading=10,
    )

    elements = []

    # ── Title ──────────────────────────────────────────────────────
    elements.append(Paragraph(
        "VOICESHIELD AI — FORENSIC INCIDENT REPORT", title_style
    ))
    elements.append(Paragraph(
        "Confidential — For Law Enforcement Use Only", subtitle_style
    ))

    # ── Report Metadata ────────────────────────────────────────────
    report_id = str(uuid.uuid4())
    generated = datetime.now(IST).strftime("%Y-%m-%d %H:%M:%S IST")
    elements.append(Paragraph(f"<b>Report ID:</b> {report_id}", normal_style))
    elements.append(Paragraph(f"<b>Generated:</b> {generated}", normal_style))
    elements.append(Spacer(1, 0.15 * inch))

    # ── Session Metadata Table ─────────────────────────────────────
    elements.append(Paragraph("Session Metadata", heading_style))

    call_id = session_data.get("call_id", "N/A")
    start_str = _to_ist_str(session_data.get("start_time"), suffix=False)
    end_str = _to_ist_str(session_data.get("end_time"), suffix=False)
    peak_score = session_data.get("peak_score", 0.0)
    role = session_data.get("role", "N/A")
    action = session_data.get("action_taken", "N/A")

    meta_header = ["Call ID", "Start (IST)", "End (IST)", "Peak Score", "Role", "Action"]
    # Cells are Paragraphs so long values wrap inside their column instead of
    # bleeding into the neighbouring one ("IST2026-09-23..." overflow bug).
    meta_row = [
        Paragraph(str(call_id), cell_style),
        Paragraph(str(start_str), cell_style),
        Paragraph(str(end_str), cell_style),
        Paragraph(f"{float(peak_score or 0.0):.4f}", cell_style),
        Paragraph(str(role), cell_style),
        Paragraph(str(action), cell_style),
    ]

    meta_table = Table(
        [meta_header, meta_row],
        colWidths=[1.05 * inch, 1.4 * inch, 1.4 * inch, 0.85 * inch, 0.55 * inch, 1.35 * inch],
    )
    meta_table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#1a237e")),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.whitesmoke),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, 0), 9),
        ("ALIGN", (1, 1), (5, 1), "CENTER"),
        ("BACKGROUND", (0, 1), (-1, -1), colors.HexColor("#e8eaf6")),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
        ("FONTSIZE", (0, 1), (-1, -1), 8),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("TOPPADDING", (0, 0), (-1, -1), 6),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
    ]))
    elements.append(meta_table)
    elements.append(Spacer(1, 0.15 * inch))

    # ── Risk Score ──────────────────────────────────────────────────
    elements.append(Paragraph("Risk Score", heading_style))

    risk_score = float(peak_score or 0.0)
    risk_role = str(role) if isinstance(role, str) else "adult"
    band = str(session_data.get("risk_band") or risk_band(risk_score, risk_role))
    thr = session_data.get("threshold")
    threshold = float(thr) if thr not in (None, "") else threshold_for(risk_role)
    verdict = str(session_data.get("verdict") or verdict_for(band, risk_role))

    risk_rows = [
        ["Peak fused score", f"{risk_score:.4f}   ({risk_score * 100:.1f}%)"],
        ["Risk band", band.capitalize()],
        ["Role / threshold", f"{risk_role}  /  {threshold:.2f}"],
        ["Verdict", verdict.capitalize()],
        ["Action taken", str(action)],
    ]
    risk_label = ParagraphStyle(
        "RiskLbl", parent=cell_style, fontName="Helvetica-Bold", textColor=colors.HexColor("#1a237e"),
    )
    risk_table = Table(
        [[Paragraph(k, risk_label), Paragraph(str(v), cell_style)] for k, v in risk_rows],
        colWidths=[1.6 * inch, 5.0 * inch],
    )
    risk_table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (0, -1), colors.HexColor("#e8eaf6")),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("TOPPADDING", (0, 0), (-1, -1), 5),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
        ("LEFTPADDING", (0, 0), (-1, -1), 8),
    ]))
    elements.append(risk_table)
    elements.append(Spacer(1, 0.15 * inch))

    # ── Peak Risk XAI Snapshot ─────────────────────────────────────
    elements.append(Paragraph("Peak Risk XAI Snapshot", heading_style))

    prosodics = session_data.get("peak_prosodics") or {}
    xai_header = ["Jitter %", "Shimmer %", "Phase Cont.", "Pitch Stab. %"]
    xai_row = [
        f"{prosodics.get('jitter_pct', 0):.2f}%",
        f"{prosodics.get('shimmer_pct', 0):.2f}%",
        f"{prosodics.get('phase_continuity', 0):.4f}",
        f"{prosodics.get('pitch_stability_pct', 0):.1f}%",
    ]

    xai_table = Table(
        [xai_header, xai_row],
        colWidths=[1.5 * inch] * 4,
    )
    xai_table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#1a237e")),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.whitesmoke),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, 0), 9),
        ("ALIGN", (0, 0), (-1, -1), "CENTER"),
        ("BACKGROUND", (0, 1), (-1, -1), colors.HexColor("#fce4ec")),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
        ("FONTSIZE", (0, 1), (-1, -1), 9),
        ("TOPPADDING", (0, 0), (-1, -1), 6),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
    ]))
    elements.append(xai_table)
    elements.append(Spacer(1, 0.15 * inch))

    # ── Score Timeline ─────────────────────────────────────────────
    elements.append(Paragraph("Score Timeline", heading_style))

    history = session_data.get("history", [])
    if history:
        timeline_header = ["#", "Timestamp (IST)", "Synthetic Score"]
        timeline_rows = [timeline_header]
        for entry in history[:30]:  # Cap at 30 entries for page space
            idx = entry.get("window_index", "—")
            ts = _to_ist_str(entry.get("timestamp"), suffix=False)
            score = entry.get("synthetic_score", 0.0)
            # Color-code score
            timeline_rows.append([str(idx), ts, f"{score:.4f}"])

        timeline_table = Table(
            timeline_rows,
            colWidths=[0.5 * inch, 2.5 * inch, 1.5 * inch],
        )

        # Build row-level styling for alternating colors
        style_cmds = [
            ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#455a64")),
            ("TEXTCOLOR", (0, 0), (-1, 0), colors.whitesmoke),
            ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
            ("FONTSIZE", (0, 0), (-1, -1), 8),
            ("ALIGN", (0, 0), (-1, -1), "CENTER"),
            ("GRID", (0, 0), (-1, -1), 0.5, colors.lightgrey),
            ("TOPPADDING", (0, 0), (-1, -1), 3),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 3),
        ]
        for i in range(1, len(timeline_rows)):
            bg = colors.HexColor("#f5f5f5") if i % 2 == 0 else colors.white
            style_cmds.append(("BACKGROUND", (0, i), (-1, i), bg))

        timeline_table.setStyle(TableStyle(style_cmds))
        elements.append(timeline_table)
    else:
        elements.append(Paragraph("<i>No timeline data available.</i>", normal_style))

    elements.append(Spacer(1, 0.25 * inch))

    # ── Legal / Compliant Next Steps ───────────────────────────────
    elements.append(Paragraph("Legal / Compliant Next Steps", heading_style))

    legal_steps = [
        "File a complaint at <b>https://cybercrime.gov.in</b> (I4C National Cybercrime Reporting Portal)",
        "Call the Cybercrime Helpline: <b>1930</b> (available 24/7)",
        "Contact your local <b>Cyber Police Station</b> with this report",
        "For financial fraud: Contact your <b>bank immediately</b> and file an RBI complaint",
        "For suspected unauthorised financial apps/entities: report on the <b>RBI Sachet</b> portal (<b>https://sachet.rbi.org.in</b>)",
        "Preserve this report as evidence — <b>do not modify</b>",
    ]
    for step in legal_steps:
        elements.append(Paragraph(f"• {step}", bullet_style))

    # ── Blockchain Evidence ─────────────────────────────────────────
    if blockchain:
        elements.append(Spacer(1, 0.15 * inch))
        elements.append(Paragraph("Blockchain Evidence (Immutable Anchor)", heading_style))
        anchor_style = ParagraphStyle(
            "Anchor", parent=normal_style,
            fontName="Courier", fontSize=8.5,
            backColor=colors.HexColor("#f1f3f9"),
            borderColor=colors.HexColor("#c5cae9"),
            borderWidth=0.5,
            leftIndent=6, rightIndent=6,
            spaceAfter=6, leading=11,
        )
        call = blockchain.get("call_id", "")
        anchor_lines = [
            f"Chain             : {blockchain.get('chain_id', 'VoiceShieldAIV1')}",
            f"Report call       : {call}",
            f"Verification API  : GET /api/blockchain/verify/call/{call}",
            f"Fabric/IPFS check : GET /api/blockchain/onchain/{call}",
        ]
        elements.append(Paragraph("<br/>".join(anchor_lines), anchor_style))
        elements.append(Paragraph(
            "<i>This report and its per-window evidence are cryptographically committed to a "
            "tamper-evident hash chain (SHA-256 + proof-of-work). The chain record stores this "
            "file's SHA-256 together with a Merkle root of the score timeline; any modification "
            "to the report invalidates verification.\n\n"
            "When the NBF-Lite external anchor is enabled, an encrypted copy of this PDF is "
            "pinned to IPFS (raw ciphertext stays under operator custody) and the block hash, "
            "Merkle root, file SHA-256, IPFS CID and key fingerprint are recorded on the "
            "Hyperledger Fabric ledger. Verify the public anchor with "
            "GET /api/blockchain/onchain/{call_id} — it fetches the on-chain record, pulls and "
            "decrypts the IPFS copy using the org-derived report key, recomputes the SHA-256 and "
            "confirms a %PDF document. Fail-open: the local PoW chain remains authoritative if "
            "the Fabric node is unreachable.</i>",
            normal_style,
        ))

    # ── Build PDF ──────────────────────────────────────────────────
    doc.build(elements, onFirstPage=_add_footer, onLaterPages=_add_footer)
    logger.info(f"Forensic PDF generated: {output_path}")

    return output_path
