# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import voiceshield_pb2 as voiceshield__pb2

GRPC_GENERATED_VERSION = '1.84.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in voiceshield_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class VoiceShieldStub:
    """── Service ───────────────────────────────────────────────────────────────

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Detect = channel.unary_unary(
                '/voiceshield.v1.VoiceShield/Detect',
                request_serializer=voiceshield__pb2.DetectRequest.SerializeToString,
                response_deserializer=voiceshield__pb2.DetectResponse.FromString,
                _registered_method=True)
        self.Analyze = channel.unary_unary(
                '/voiceshield.v1.VoiceShield/Analyze',
                request_serializer=voiceshield__pb2.AnalyzeRequest.SerializeToString,
                response_deserializer=voiceshield__pb2.AnalyzeResponse.FromString,
                _registered_method=True)
        self.ListIncidents = channel.unary_unary(
                '/voiceshield.v1.VoiceShield/ListIncidents',
                request_serializer=voiceshield__pb2.ListIncidentsRequest.SerializeToString,
                response_deserializer=voiceshield__pb2.ListIncidentsResponse.FromString,
                _registered_method=True)
        self.GetIncident = channel.unary_unary(
                '/voiceshield.v1.VoiceShield/GetIncident',
                request_serializer=voiceshield__pb2.GetIncidentRequest.SerializeToString,
                response_deserializer=voiceshield__pb2.Incident.FromString,
                _registered_method=True)
        self.Acknowledge = channel.unary_unary(
                '/voiceshield.v1.VoiceShield/Acknowledge',
                request_serializer=voiceshield__pb2.AcknowledgeRequest.SerializeToString,
                response_deserializer=voiceshield__pb2.AcknowledgeResponse.FromString,
                _registered_method=True)
        self.Escalate = channel.unary_unary(
                '/voiceshield.v1.VoiceShield/Escalate',
                request_serializer=voiceshield__pb2.EscalateRequest.SerializeToString,
                response_deserializer=voiceshield__pb2.EscalateResponse.FromString,
                _registered_method=True)
        self.GetWorkflows = channel.unary_unary(
                '/voiceshield.v1.VoiceShield/GetWorkflows',
                request_serializer=voiceshield__pb2.GetWorkflowsRequest.SerializeToString,
                response_deserializer=voiceshield__pb2.GetWorkflowsResponse.FromString,
                _registered_method=True)
        self.VerifyCall = channel.unary_unary(
                '/voiceshield.v1.VoiceShield/VerifyCall',
                request_serializer=voiceshield__pb2.VerifyCallRequest.SerializeToString,
                response_deserializer=voiceshield__pb2.VerifyCallResponse.FromString,
                _registered_method=True)
        self.RetryAnchor = channel.unary_unary(
                '/voiceshield.v1.VoiceShield/RetryAnchor',
                request_serializer=voiceshield__pb2.RetryAnchorRequest.SerializeToString,
                response_deserializer=voiceshield__pb2.RetryAnchorResponse.FromString,
                _registered_method=True)
        self.RegisterSpeaker = channel.unary_unary(
                '/voiceshield.v1.VoiceShield/RegisterSpeaker',
                request_serializer=voiceshield__pb2.RegisterSpeakerRequest.SerializeToString,
                response_deserializer=voiceshield__pb2.RegisterSpeakerResponse.FromString,
                _registered_method=True)


class VoiceShieldServicer:
    """── Service ───────────────────────────────────────────────────────────────

    """

    def Detect(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Analyze(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListIncidents(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetIncident(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Acknowledge(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Escalate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetWorkflows(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def VerifyCall(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RetryAnchor(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RegisterSpeaker(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_VoiceShieldServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Detect': grpc.unary_unary_rpc_method_handler(
                    servicer.Detect,
                    request_deserializer=voiceshield__pb2.DetectRequest.FromString,
                    response_serializer=voiceshield__pb2.DetectResponse.SerializeToString,
            ),
            'Analyze': grpc.unary_unary_rpc_method_handler(
                    servicer.Analyze,
                    request_deserializer=voiceshield__pb2.AnalyzeRequest.FromString,
                    response_serializer=voiceshield__pb2.AnalyzeResponse.SerializeToString,
            ),
            'ListIncidents': grpc.unary_unary_rpc_method_handler(
                    servicer.ListIncidents,
                    request_deserializer=voiceshield__pb2.ListIncidentsRequest.FromString,
                    response_serializer=voiceshield__pb2.ListIncidentsResponse.SerializeToString,
            ),
            'GetIncident': grpc.unary_unary_rpc_method_handler(
                    servicer.GetIncident,
                    request_deserializer=voiceshield__pb2.GetIncidentRequest.FromString,
                    response_serializer=voiceshield__pb2.Incident.SerializeToString,
            ),
            'Acknowledge': grpc.unary_unary_rpc_method_handler(
                    servicer.Acknowledge,
                    request_deserializer=voiceshield__pb2.AcknowledgeRequest.FromString,
                    response_serializer=voiceshield__pb2.AcknowledgeResponse.SerializeToString,
            ),
            'Escalate': grpc.unary_unary_rpc_method_handler(
                    servicer.Escalate,
                    request_deserializer=voiceshield__pb2.EscalateRequest.FromString,
                    response_serializer=voiceshield__pb2.EscalateResponse.SerializeToString,
            ),
            'GetWorkflows': grpc.unary_unary_rpc_method_handler(
                    servicer.GetWorkflows,
                    request_deserializer=voiceshield__pb2.GetWorkflowsRequest.FromString,
                    response_serializer=voiceshield__pb2.GetWorkflowsResponse.SerializeToString,
            ),
            'VerifyCall': grpc.unary_unary_rpc_method_handler(
                    servicer.VerifyCall,
                    request_deserializer=voiceshield__pb2.VerifyCallRequest.FromString,
                    response_serializer=voiceshield__pb2.VerifyCallResponse.SerializeToString,
            ),
            'RetryAnchor': grpc.unary_unary_rpc_method_handler(
                    servicer.RetryAnchor,
                    request_deserializer=voiceshield__pb2.RetryAnchorRequest.FromString,
                    response_serializer=voiceshield__pb2.RetryAnchorResponse.SerializeToString,
            ),
            'RegisterSpeaker': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterSpeaker,
                    request_deserializer=voiceshield__pb2.RegisterSpeakerRequest.FromString,
                    response_serializer=voiceshield__pb2.RegisterSpeakerResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'voiceshield.v1.VoiceShield', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('voiceshield.v1.VoiceShield', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class VoiceShield:
    """── Service ───────────────────────────────────────────────────────────────

    """

    @staticmethod
    def Detect(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/voiceshield.v1.VoiceShield/Detect',
            voiceshield__pb2.DetectRequest.SerializeToString,
            voiceshield__pb2.DetectResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Analyze(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/voiceshield.v1.VoiceShield/Analyze',
            voiceshield__pb2.AnalyzeRequest.SerializeToString,
            voiceshield__pb2.AnalyzeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListIncidents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/voiceshield.v1.VoiceShield/ListIncidents',
            voiceshield__pb2.ListIncidentsRequest.SerializeToString,
            voiceshield__pb2.ListIncidentsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetIncident(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/voiceshield.v1.VoiceShield/GetIncident',
            voiceshield__pb2.GetIncidentRequest.SerializeToString,
            voiceshield__pb2.Incident.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Acknowledge(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/voiceshield.v1.VoiceShield/Acknowledge',
            voiceshield__pb2.AcknowledgeRequest.SerializeToString,
            voiceshield__pb2.AcknowledgeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Escalate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/voiceshield.v1.VoiceShield/Escalate',
            voiceshield__pb2.EscalateRequest.SerializeToString,
            voiceshield__pb2.EscalateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetWorkflows(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/voiceshield.v1.VoiceShield/GetWorkflows',
            voiceshield__pb2.GetWorkflowsRequest.SerializeToString,
            voiceshield__pb2.GetWorkflowsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def VerifyCall(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/voiceshield.v1.VoiceShield/VerifyCall',
            voiceshield__pb2.VerifyCallRequest.SerializeToString,
            voiceshield__pb2.VerifyCallResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RetryAnchor(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/voiceshield.v1.VoiceShield/RetryAnchor',
            voiceshield__pb2.RetryAnchorRequest.SerializeToString,
            voiceshield__pb2.RetryAnchorResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RegisterSpeaker(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/voiceshield.v1.VoiceShield/RegisterSpeaker',
            voiceshield__pb2.RegisterSpeakerRequest.SerializeToString,
            voiceshield__pb2.RegisterSpeakerResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
